"""add unique constraint to regions

Revision ID: 147d4da75dd2
Revises: 724e586738b5
Create Date: 2026-01-23 00:45:01.881284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147d4da75dd2'
down_revision: Union[str, Sequence[str], None] = '724e586738b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_regions_country_region', 'regions', ['country_code', 'region_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_regions_country_region', 'regions', type_='unique')
    # ### end Alembic commands ###
