"""create core tables

Revision ID: 724e586738b5
Revises: 5f114d95d095
Create Date: 2026-01-22 23:20:36.618094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '724e586738b5'
down_revision: Union[str, Sequence[str], None] = '5f114d95d095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.Column('city_type', sa.String(length=16), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('base_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_country_code'), 'regions', ['country_code'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('selected_region_id', sa.UUID(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_line', sa.String(length=255), nullable=True),
    sa.Column('reasons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('next_steps', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_device_id'), 'tests', ['device_id'], unique=False)
    op.create_index(op.f('ix_tests_selected_region_id'), 'tests', ['selected_region_id'], unique=False)
    op.create_table('test_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('text_answer', sa.String(), nullable=True),
    sa.Column('selected_options', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_answers_question_id'), 'test_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_test_answers_test_id'), 'test_answers', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_answers_test_id'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_question_id'), table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index(op.f('ix_tests_selected_region_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_device_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_regions_country_code'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
