"""add indexes

Revision ID: d6d4c68700b1
Revises: 147d4da75dd2
Create Date: 2026-01-23 17:51:54.026284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d4c68700b1'
down_revision: Union[str, Sequence[str], None] = '147d4da75dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tests_device_id_created_at', 'tests', ['device_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tests_device_id_created_at', table_name='tests')
    # ### end Alembic commands ###
